SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_CROSSCOMPILING 1)
set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")

if (NOT GCC_TRIPLE)
    set(GCC_TRIPLE "riscv64-unknown-elf")
endif()

set(CMAKE_C_COMPILER   "${GCC_TRIPLE}-gcc")
set(CMAKE_CXX_COMPILER "${GCC_TRIPLE}-g++")
